### PR TITLE
fix: use SplayTreeSet to resolve inconsistent hashCode

### LINKED ISSUE #141: Equality and Hashcode differ for Sets with different order
**Describe the bug**
For properties of type `Set` the result of `hashCode` is unexpected.
Equality works like expected (order of Set elements doesn't have an impact) but `hashCode` produces different values depending on the order in the Set.

**To Reproduce**

```dart
import 'package:equatable/equatable.dart';

class EquatableWithSet extends Equatable {
  final Set<int> intSet;

  EquatableWithSet(this.intSet);

  @override
  List<Object?> get props => [
        intSet,
      ];
}

void main(List<String> arguments) {
  final obj1 = EquatableWithSet({1,2,3});
  final obj2 = EquatableWithSet({3,1,2});

  assert(obj1 == obj2, 'Are not equal!');
  assert(obj1.hashCode == obj2.hashCode, 'Don\'t have the same hashcode!');
}
```

**Expected behavior**
Two objects that are equal also have the same hashCode (independent of the order in the Set)

**Screenshots**

**Version**
`Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "macos_x64"`

**Additional context**

### PR DESCRIPTION
**Pull request by devmil**
Fixes #141

## Status
**READY**

## Breaking Changes
NO

## Description
This fixes the inconsistent hashCode behaviour for Sets by using a SplayTreeSet to ensure a consistent iteration order.

## Todos
- [x] Tests
- [ ] Documentation
- [ ] Examples

## Steps to Test or Reproduce
See #141

## Impact to Remaining Code Base
None known

### CODE REVIEW

File: lib/src/equatable_utils.dart [hunk 1]
```diff
@@ -46,6 +48,11 @@ int _combine(int hash, dynamic object) {
     });
     return hash;
   }
+  if(object is Set) {
```
Comment (felangel) [inline lib/src/equatable_utils.dart:51]:
```suggestion
  if (object is Set) {
```

File: lib/src/equatable_utils.dart [hunk 2]
```diff
@@ -46,6 +48,11 @@ int _combine(int hash, dynamic object) {
     });
     return hash;
   }
+  if (object is Set) {
```
Comment (felangel) [inline lib/src/equatable_utils.dart:51]: should we also check to make sure `object` is not already a `SplayTreeSet` to avoid unnecessarily created a new instance?
```suggestion
  if (object is Set && object is! SplayTreeSet) {
```

Comment (devmil) [reply lib/src/equatable_utils.dart:51]: Good point!

**Comment by felangel** [comment]
@devmil thanks for the contribution! I’ll merge and publish this tomorrow 👍

**Review by felangel — APPROVED** [review]
